### ISSUE TITLE
Multiple user roles

### ISSUE THREAD

**Issue by tiagoleal25** [ixis/codeception-module-drupal-user-registry#10]
Hi @pfaocle,

one user can have multiple roles?

Best regards!

**Comment by pfaocle** [comment]
Yep - this wasn't a use case for our projects when we originally put the module together, but is a common way Drupal users/roles are configured. We hope to allow for this in the future, but until we suss it out suggestions and pull requests are most welcome!

**Comment by pfaocle** [comment]
Marking as a duplicate of PR #14
