### ISSUE TITLE
Strict warning: Incompatible declaration of _beforeSuite() 

### ISSUE THREAD

**Issue by JorisVanEijden** [ixis/codeception-module-drupal-user-registry#16]
Strict standards: Declaration of 

    Codeception\Module\DrupalUserRegistry::_beforeSuite()
should be compatible with 

    Codeception\Module::_beforeSuite($settings = Array)

**Comment by pfaocle** [comment]
This should be addressed on develop branch and soon in the next tagged dev release, 0.1.1
